language: python
dist: bionic
os: linux

python:
  - "2.7"
  - "3.8"

compiler:
  - gcc

cache:
  apt: true

git:
  depth: 3

branches:
  only:
  - master

jobs:
  include:
    - name: "GNU Compiler Collection 7"
      env: CC=gcc-7 CXX=g++-7
      addons:
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - name: "GNU Compiler Collection 8"
      env: CC=gcc-8 CXX=g++-8
      addons:
        apt:
          sources: *sources
          packages:
            - g++-8
    - name: "GNU Compiler Collection 9"
      env: CC=gcc-9 CXX=g++-9
      addons:
        apt:
          sources: *sources
          packages:
            - g++-9
script:
  - export CXXFLAGS="-g -Wall"
  - export STRIP="strip"
  - make
  - python -m compileall -l .
  - find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
