language: python
dist: bionic
os: linux

python:
  - "2.7"
  - "3.5"
  - "3.8"

compiler:
  - gcc

cache:
  apt: true

git:
  depth: 3

branches:
  only:
  - master

install:
  - pip install flake8

jobs:
  include:
    - name: "GNU Compiler Collection 7"
      env: CC=gcc-7 CXX=g++-7
      addons:
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - name: "GNU Compiler Collection 8"
      env: CC=gcc-8 CXX=g++-8
      addons:
        apt:
          sources: *sources
          packages:
            - g++-8
    - name: "GNU Compiler Collection 9"
      env: CC=gcc-9 CXX=g++-9
      addons:
        apt:
          sources: *sources
          packages:
            - g++-9
    - name: "GNU Compiler Collection 10"
      env: CC=gcc-10 CXX=g++-10
      addons:
        apt:
          sources: *sources
          packages:
            - g++-10

script:
  - export CXXFLAGS="-g -Wall"
  - export STRIP="strip"
  - make
  - python -m compileall -l .
  - find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
  - flake8 --ignore=W191,E128,E501,E722 . --exit-zero

# PEP8 :- IGNORE CODES
# W191 : indentation contains tabs
# E128 : continuation line under-indented for visual indent
# E501 : line too long (> 79 characters)
# E722 : do not use bare 'except'

