#!/bin/sh
# AutoBouquetsIptvEPG for 28.2E by LraiZer
# script tool for use after running BMX,JMX and AutoBouquets
# auto assigns jmx,bmx iptv bouquets with service stream epg
# satellite references generated by AutoBouquets E2 for 28.2E.

VERSIONDATE="21 Apr 2025"

# enable/disable service description truncation renaming ["True"/"False"]
IPTV_SERVICE_RENAME="True"

# assign a search filter to limit the conversion to only matching bouquets
# ie. "IPTV_UK*SPORT" finds userbouquet.bmx_live_IPTV_UK_FREE_SPORTS_HD.tv

#BOUQUET_FILTER="IPTV_UK*SPORT"
BOUQUET_FILTER="_live_"

# assign a channel id for alias names that change often
# or are not automatically found by the detection logic
# channelid=iptvname,iptvname,iptvname,iptvname,...

CHANNEL_ID_ALIAS="
1003=MUTVHD,MANCHESTERUNITED
1103=NOW90s00s,NOWXMAS
1121=FRANCE24HD,FranceEng
1136=SkyDocmntrsHD,SkyDocumentariesHD
1199=SkyAnimationHD
1289=PremierSports1,PremierSport1,Viaplay1HD,ViaplaySports1,ViaplaySport1
1290=PremierSports2,PremierSport2,Viaplay2HD,ViaplaySports2,ViaplaySport2,ViaplayExtra,ViaPlayXtra
1336=TNTUltimateUHD,TNTSportsUltimateUHD
1409=SkyPremiere
1633=PremierSports1IrelandHD
1635=PremierSports2IrelandHD
1821=NDTVWorld,NDTV24x7
1849=Nicktoons
1872=Together,togetherTV
2053=BBCRB1HD,BBCRedButton
2402=AnimalPlanet,AnimalPlntHD
2508=MTV90s,MTVXMAS
3000=BBCOneLonHD,BBCOneHD
3007=BBCOneNWHD,BBCOneNorthWest
3020=BBCParlHD,BBCParliament
3354=JewelleryMaker,JewelryMaker
3592=FoodNetwrk+1,FoodNetwork+1
3617=TRUECRIMEX,TrueCrimeXtra
3636=RacingTV,RacingUK
3751=Gromance+1,GreatRomance+1
3835=SkySpF1HD,SkySpDARTSHD
4014=SkyActionHD
4015=SkyGreatsHD
4016=SkyDramaHD,SkyDramaRomHD
4017=SkySciFi/HorrorHD
4018=SkyFamilyHD
4019=SkyComedyHD
4020=SkySelectHD
4021=SkyPremiereHD
4022=SkySpActionHD,SkySpNFLHD
4033=SkyHitsHD
4062=SkyThrillerHD
4340=NickJr.Too
4420=Movies24
5272=RacingTVHD,RacingUKHD
5601=CartoonNetwrk,CartoonNetwork
6504=ITV1LondonHD,ITV1HD
7211=SkySpMEUHD,SkySpMainEvUHD
7221=SkySpUltraHD01,SkySp1
9002=SkySpUltraHD02,SkySp2
"

start_time=`date +%s`
E2BQ_PATH="/etc/enigma2"
IEPG_PATH="/tmp/iepg"
AUTOBOUQUETS_PATH=/usr/lib/enigma2/python/Plugins/Extensions/AutoBouquets
echo "AutoBouquets IptvEPG for 28.2E - version $VERSIONDATE"
#echo -e "`date`\n\nCHANNEL_ID_ALIAS missing services log\n" > /tmp/autoiepg_log.txt
#echo -e `date` > /tmp/servicename.txt
if [ -e $AUTOBOUQUETS_PATH/autobouquets.csv ]; then
	BOUQUETS_CSV=`sed 1d $AUTOBOUQUETS_PATH/autobouquets.csv | sed "s/[ ~!#-']//g"`
	COUNT=0
	OIFS=$IFS
	IFS='
'
	echo "Converting $BOUQUET_FILTER bouquets, working..."
	for BOUQUET in `ls $E2BQ_PATH/*$BOUQUET_FILTER*.tv`; do
		SERVICES=`grep -i '^#SERVICE.*http*' $BOUQUET`
		if [ $(echo "$SERVICES"|wc -l) -lt 2 ]; then
		 continue
		fi
		COUNT=$(($COUNT + 1))
		if [ $COUNT -eq 1 ]; then
			mkdir -p $IEPG_PATH
		fi
		cp $BOUQUET $IEPG_PATH
	done
	if [ $COUNT -eq 0 ]; then
		echo "No live UK services"
		exit 0
	fi

	COUNT=0
	for BOUQUET in `ls $IEPG_PATH/userbouquet.*$BOUQUET_FILTER*.tv`; do
		SERVICES=`grep -i '^#SERVICE.*http*' $BOUQUET`
		for SERVICE_IPTV in $SERVICES; do
			COUNT=$((COUNT + 1));
			#echo -ne "#$COUNT\r"
			SERVICE_NAME_IPTV=`echo "$SERVICE_IPTV" | grep -o '[^:]\+$'`
			SERVICE_NAME=`echo "$SERVICE_NAME_IPTV" |\
			sed "s/⚽/O/g;s/ᴿᴬᵂ\|ʰᵉᵛᶜ\|ᵁᴴᴰ\|ᴴᴰ\|⁴ᵏ\|³⁸⁴⁰ᴾ\|◉\|⁽ᴮᴷ²⁾\|ᵃᵐᶻ\|⁵⁰//g" |\
			sed "s/ITV /ITV1/ig;s/Sky Sports/SkySp/ig;s/TNT Sport \|TNT Sports/TNTSports/ig;s/Box Office/BoxOff/ig" |\
			sed "s/Main Event\|Main Events/Main Ev/ig;s/Football/F\'ball/ig;s/Premier League/PL/ig" |\
			sed "s/FHD/HD/ig;s/4k\|50 fps//ig;s/HEVC\|VIP\|FPS\|BFBS \|UK \| SD\|SkyGo //ig;s/[ ~!#-'&]//g"`
			#echo "$SERVICE_NAME = $SERVICE_NAME_IPTV" >>/tmp/servicename.txt
			if ! `echo "$BOUQUETS_CSV" | grep -i -q -m 1 "$SERVICE_NAME"`; then
				if `echo "$CHANNEL_ID_ALIAS" | grep -i -q -m 1 "$SERVICE_NAME"`; then
					CHANNEL_ID=`echo "$CHANNEL_ID_ALIAS" | grep -i -m 1 "$SERVICE_NAME"  | cut -d '=' -f 1`
					SERVICE_CSV=`echo "$BOUQUETS_CSV" | grep -m 1 ",$CHANNEL_ID,"`
					SERVICE_REF=`echo "$SERVICE_CSV" | cut -d "," -f 8 | cut -c 2-`
				else
					#echo "$SERVICE_NAME" >> /tmp/autoiepg_log.txt
					continue
				fi
			else
				SERVICE_CSV=`echo "$BOUQUETS_CSV" | grep -i -m 1 "$SERVICE_NAME"`
				SERVICE_REF=`echo "$SERVICE_CSV" | cut -d "," -f 8 | cut -c 2-`
			fi
			SERVICE_STREAM=`echo "$SERVICE_IPTV" | sed 's/^#SERVICE *....\(.*\)http.*$/\1/'`
			sed -i s"/$SERVICE_STREAM/$SERVICE_REF/" "$BOUQUET"
			if [ "$IPTV_SERVICE_RENAME" == "True" ]; then
				[[ "$SERVICE_NAME_IPTV" == "~"* ]] && SERVICE_NAME="~$SERVICE_NAME"
				sed -i s"/#DESCRIPTION $SERVICE_NAME_IPTV/#DESCRIPTION $SERVICE_NAME/" "$BOUQUET"
			fi
			#echo "service updated:$SERVICE_STREAM $SERVICE_NAME" >> /tmp/autoiepg_log.txt
		done
	done
	IFS=$OIFS
	mv $IEPG_PATH/*$BOUQUET_FILTER*.tv $E2BQ_PATH
	rm -rf $IEPG_PATH
else
	echo -e "missing autobouquets.csv:\nAutoBouquets IptvEPG requires AutoBouquets to run first!"
fi
stop_time=$(expr `date +%s` - $start_time)
log_time="Process Time: $COUNT services in "$(expr $stop_time / 60)" minutes "$(expr $stop_time % 60)" seconds."
echo "$log_time"; wget -q -O - http://127.0.0.1/web/servicelistreload?mode=2 >/dev/null 2>&1
